### ISSUE TITLE
qsrv does not honor pvRequest

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/pva2pva#1]
An example for get is:

mrk> pvget DBRdouble00
DBRdouble00                    0
mrk> pvget -r "field(value)" DBRdouble00
DBRdouble00
epics:nt/NTScalar:1.0 
    double value 0
    alarm_t alarm INVALID NO_STATUS <no message>
    time_t timeStamp <undefined> 0
    display_t display
        double limitLow 0
        double limitHigh 0
        string description 
        string format 
        string units 
    control_t control
        double limitLow 0
        double limitHigh 0
        double minStep 0

An example for put is

mrk> pvput -r "display.limitHigh" DBRdouble00 5
Old : 
epics:nt/NTScalar:1.0 
    double value 0
    alarm_t alarm
        int severity 3
        int status 0
        string message 
    time_t timeStamp
        long secondsPastEpoch 631152000
        int nanoseconds 0
        int userTag 0
    display_t display
        double limitLow 0
        double limitHigh 0
        string description 
        string format 
        string units 
    control_t control
        double limitLow 0
        double limitHigh 0
        double minStep 0

New : 
epics:nt/NTScalar:1.0 
    double value 5
    alarm_t alarm
        int severity 0
        int status 0
        string message 
    time_t timeStamp
        long secondsPastEpoch 1507112401
        int nanoseconds 523035574
        int userTag 0
    display_t display
        double limitLow 0
        double limitHigh 0
        string description 
        string format 
        string units 
    control_t control
        double limitLow 0
        double limitHigh 0
        double minStep 0

I think the same problem existed for pvaSrv

**Comment by mdavidsaver** [comment]
QSRV doesn't (and probably won't ever) support _changing_ meta-data fields via put.  IMO, to support this would require additions to the record support API to handle this operation.  For the moment, I think this is beyond the scope of QSRV.

> pvput -r "display.limitHigh" DBRdouble00 5

What you intend is:

> pvput  DBRdouble00 display.limitHigh=5
