### ISSUE TITLE
64-bit integer field access is broken

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/pva2pva#25]
On 1/8/19 3:08 AM, Timo Korhonen via Core-talk wrote:
> Hi all,
> 
> I made a quick try to use the 64-bit record types (int64in/int64out) with base 7.0.2.
> 
> Trying to pvget the record, I get the following message on the IOC console:
> 
> epics> 2019-01-08T11:43:50.309 an exception caught while in receiveThread at ../../src/remote/codec.cpp:1144: Unsupported DBR code
> 
> And pvget times out. With caget, I can read the value but as expected, I do not get the 64-bit integer (because ca does not support it, obviously). 
> 
> Any ideas? Maybe I am missing some configuration, but I could not figure out from the release notes if I needed to do something extra.
> 
> This is on Mac OSX El Capitan, 10.11.6. I can try other platforms later but at the first sight this does not appear to be a platform-specific issue.
> 
> Timo
> 

@ttkorhonen

**Comment by mdavidsaver** [comment]
Should be fixed as of 7bc5cbf9573386afb8ef606e543b50635bebf73a .  @ttkorhonen please pull down the latest and re-test.

**Comment by ttkorhonen** [comment]
Rebuilt and tested, works now. Thanks Michael!
