### ISSUE TITLE
softIocPVA assumes INSTALL_LOCATION=EPICS_BASE

### ISSUE THREAD

**Issue by anjohnson** [epics-base/pva2pva#27]
When pva2pva is built as an external module, the `EXIT_FILE` macro in `softMain.c` doesn't point to the `softIocExit.db` file in `$(EPICS_BASE)/db`.

The assumption in the code is that `EXIT_FILE` is always available relative to `$(INSTALL_LOCATION)` but building pva2pva as a stand-alone module breaks that assumption. The locally-created `softIocPVA.dbd` file is loaded correctly, but the `softIocExit.db` database is would have to be loaded from `$(EPICS_BASE)/db`.

The simplest fix is to make a local copy of the database file when doing stand-alone builds. The change below does that (no conditionals are needed to distinguish them from regular builds). This is tested, and I can commit if you're Okay with it.

```patch
diff --git a/pdbApp/Makefile b/pdbApp/Makefile
index 8bd41a2..c54e769 100644
--- a/pdbApp/Makefile
+++ b/pdbApp/Makefile
@@ -73,6 +73,8 @@ softIocPVA_LIBS += $(EPICS_BASE_IOC_LIBS)
 DBD += softIocPVA.dbd
 DBD += qsrv.dbd
 
+DB_INSTALLS += $(EPICS_BASE)/db/softIocExit.db
+
 softIocPVA_DBD += softIoc.dbd
 softIocPVA_DBD += PVAServerRegister.dbd
 softIocPVA_DBD += qsrv.dbd
```

**Comment by mdavidsaver** [comment]
This should have a conditional to avoid clobbering when `$(INSTALL_LOCATION)==$(EPICS_BASE)` but otherwise looks fine.

```make
ifneq ($(INSTALL_LOCATION),$(EPICS_BASE))
DB_INSTALLS += $(EPICS_BASE)/db/softIocExit.db
endif
```

**Comment by anjohnson** [comment]
As I said above (and have already tested), no conditional is required for regular builds under the base-7.0 modules directory because that case degenerates to this make rule, which GNUmake knows is a no-op:
```makefile
$(EPICS_BASE)/db/softIocExit.db: $(EPICS_BASE)/db/softIocExit.db
```

**Comment by mdavidsaver** [comment]
> for regular builds

With my debian packager hat on.  The conditional also handles the `$(FINAL_LOCATION)!=$(INSTALL_LOCATION)` case.  I've tripped over this before with `DB_INSTALLS`.

**Comment by anjohnson** [comment]
GNUmake is not looking at `$(FINAL_LOCATION)` here, just `$(INSTALL_LOCATION)` and `$(EPICS_BASE)`. Since the two values are identical in this case another way of spelling the no-op rule I showed above is this:
```makefile
$(INSTALL_LOCATION)/db/softIocExit.db: $(INSTALL_LOCATION)/db/softIocExit.db
```

**Comment by mdavidsaver** [comment]
I need to be clearer.  The situation during a debian package build is

- EPICS_BASE=/usr/lib/epics
- FINAL_LOCATION=/usr/lib/epics
- INSTALL_LOCATION=/tmp/some/dir

This will result in softIocExit.db being copied into the temporary INSTALL_LOCATION.  This temporary directory becomes /usr/lib/epics in the .deb being created.  This would later generate a conflict during installation because both would contain `/usr/lib/epics/db/softIocExit.db`.

**Comment by anjohnson** [comment]
You suggested above:
```makefile
ifneq ($(INSTALL_LOCATION),$(EPICS_BASE))
DB_INSTALLS += $(EPICS_BASE)/db/softIocExit.db
endif
```
In a Debian build with the paths you just quoted that would become
```makefile
ifneq (/tmp/some/dir,/usr/lib/epics) # This condition is true
DB_INSTALLS += /usr/lib/epics/db/softIocExit.db
endif
```
which I suspect isn't what you actually meant. Maybe this instead?
```makefile
ifneq ($(FINAL_LOCATION),$(EPICS_BASE))
DB_INSTALLS += $(EPICS_BASE)/db/softIocExit.db
endif
```

**Comment by mdavidsaver** [comment]
> which I suspect isn't what you actually meant. Maybe this instead?

Ah, yes.  Agreed.

**Comment by anjohnson** [comment]
Committing that fix.

**Comment by mdavidsaver** [comment]
cf. 6d1cbd87fd5ee59c6892965a58a56365ade94cc7
