### ISSUE TITLE
QSRV and server side filters

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/pva2pva#32]
I've run across an issue with using QSRV and some server side filters.  Specifically those which drop events.  QSRV assumes that the first `DBE_PROPERTY` update will never be dropped.  If such an update is dropped, the subscription stalls.  I've also realized that at present a filter can't access the `DBE_*`.

Related to this.  I'm using the same `dbChannel` to create both the `DBE_VALUE` and `DBE_PROPERTY` subscription.  With the `DBE_PROPERTY` event being created second.  So, eg. the `dbnd` filter will always drop this update...

https://github.com/epics-base/pva2pva/blob/29a6f261dcd28e213d273d5b2acb0ae7408dfcb2/pdbApp/pdbsingle.cpp#L51-L56

I'm not quite certain how to handle this.  Currently, I wait for an initial event on both subscription before notifying the PVA subscriber.  This isn't required, but avoids an annoying double update when starting a subscription (one value and one meta-data).

@ralphlange

**Comment by ralphlange** [comment]
That's very similar to the longstanding issue that on subscriptions with multiple DBE_* flags set, CA does not show for any specific update _why_ it has been sent. (Same thing on a lower level.)
The Gateway works around that by creating a separate subscription for each DBE_* bit (already an optimization instead of having a separate subscription for every combination), increasing the traffic.

Adding the reason to the db_fl updates would be appropriate, but a rather heavy change.

**Comment by mdavidsaver** [comment]
> Adding the reason to the db_fl updates would be appropriate, but a rather heavy change.

This is what I'm trying.  It's a simple enough change since `db_create_event_log()` can access to `evSubscrip::select` where the subscription mask is stored.  It would require changing existing filters which drop, but there aren't too many of those.

```diff
diff --git a/modules/database/src/ioc/db/dbEvent.c b/modules/database/src/ioc/db/dbEvent.c
index 5bef0c50b..8b344d796 100644
--- a/modules/database/src/ioc/db/dbEvent.c
+++ b/modules/database/src/ioc/db/dbEvent.c
@@ -668,6 +668,7 @@ db_field_log* db_create_event_log (struct evSubscrip *pevent)
         struct dbChannel *chan = pevent->chan;
         struct dbCommon  *prec = dbChannelRecord(chan);
         pLog->ctx = dbfl_context_event;
+        pLog->mask = pevent->select;
         if (pevent->useValque) {
             pLog->type = dbfl_type_val;
             pLog->stat = prec->stat;
diff --git a/modules/database/src/ioc/db/db_field_log.h b/modules/database/src/ioc/db/db_field_log.h
index 1534517bb..11f7eceeb 100644
--- a/modules/database/src/ioc/db/db_field_log.h
+++ b/modules/database/src/ioc/db/db_field_log.h
@@ -92,6 +92,8 @@ typedef struct db_field_log {
     unsigned int     type:2;  /* type (union) selector */
     /* ctx is used for all types */
     unsigned int      ctx:1;  /* context (operation type) */
+    /* only for dbfl_context_event */
+    unsigned char      mask;  /* DBE_* mask */
     /* the following are used for value and reference types */
     epicsTimeStamp     time;  /* Time stamp */
     unsigned short     stat;  /* Alarm Status */
```
