### ISSUE TITLE
p2p: Deprecation notice missing in README

### ISSUE THREAD

**Issue by pklaus** [epics-base/pva2pva#36]
When the p2p application is being started (and then only if a config file is provided), the following notice will appear:

https://github.com/epics-base/pva2pva/blob/cda2222ed5fa22d65bef2e1d033bcb655f58b4a6/p2pApp/gwmain.cpp#L262-L270

So basically after spending all the effort of downloading the repo, compiling the software and adapting a config file I got this message the moment before I actually wanted to use it for the first time. A bit unfortunate, I'd say.

In my view, this deprecation notice is an important information that should be found prominently in the README of this project.

**Comment by mdavidsaver** [comment]
This is a reasonable point.  d100eac09eb0572c1270e986abf76e41405a6fa3

**Comment by pklaus** [comment]
That was a quick fix. Thanks!
