### ISSUE TITLE
QSRV map arrays of strings and enums

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/pva2pva#4]
Mapping of DBR_STRING and DBR_ENUM and max elements!=1 is currently not implemented.

**Comment by mdavidsaver** [comment]
fyi @anjohnson @ralphlange  @mrkraimer

**Comment by mdavidsaver** [comment]
Ha, at some point I did added the special case code to handle string array, but never removed the dbr type check.

**Comment by mdavidsaver** [comment]
f9c1489fcc24c97d36e1edd85e94c1261383282a turns on string array mapping.

```python
In [1]: from p4p.client.thread import Context

In [2]: C=Context('pva')

In [3]: C.get('arrs')
Out[3]: []

In [4]: C.put('arrs', ['hello', 'world'])

In [5]: C.get('arrs')
Out[5]: [u'hello', u'world']
```

Using an IOC w/ QSRV and

```
record(waveform, "arrs") {
  field(FTVL, "STRING")
  field(NELM, "10")
}
```

@mrkraimer Can you update and repeat your test to confirm?

**Comment by mrkraimer** [comment]
I did and now stringArray works
mrk> pvput DBRstringArray01 5 a b c d e
Old : DBRstringArray01 0
New : DBRstringArray01 5 a b c d e
mrk> pvget DBRstringArray01
DBRstringArray01 5 a b c d e

I will close issue
