### ISSUE TITLE
Allow qsrv fields to be generated in parse order

### ISSUE THREAD

**Issue by coretl** [epics-base/pva2pva#53]
From an email exchange with @mdavidsaver 

> QSRV uses the dbStatic API to access info() tags after parsing.
> Iteration order here is determined by how records are stored
> internally, which has never been entirely in parse order.
> (and is "officially" undefined)
> 
> The current scheme groups records by record type, then record
> instance.  So the loop looks something like:
> 
> > for recType in pdbbase:
> >     for rec in recType:
> >         for info in rec:
> >             if info=='Q:group':
> >                 # do something with info string
> 
> The ordering of record types is in parse order of the recordtype()
> blocks.  So practically this is determined by base.dbd.  Currently
> the relevant file is in lexical order, but it hasn't always been so.
> 
> The list of records per record type has changed.  Prior to 3.15.5
> it was sorted lexically.  Since it has been in parse order.
> Of course this is still order per record type.
> 
> It occurs to me that a smaller change to keep track of parse order
separate from iteration order should be possible.

Can we add a new parse order field when we see the record, then generate fields in the pva structure based on this? Should this be the default behaviour?

**Comment by coretl** [comment]
It would be good to do this during the codeathon in March

**Comment by anjohnson** [comment]
> Can we add a new parse order field when we see the record

We could add a global record instance counter to `pdbbase` and store its value with the record when it first gets created. However just storing the counter value with the records might not help qsrv if it needs to parse them in the same order they were loaded, to do that efficiently would probably need the IOC to keep a list of pointers to all the records in their load order. That list would be wasted memory for sites not using qsrv.

It is possible (and not uncommon) for a record to be loaded more than once; setting extra fields, creating aliases and even setting info fields are the kinds of things that frequently use additional DB files. The design needs to be aware of that kind of usage, although it might not be an issue at all as long as order-of-record-creation is sufficient.

Oh, and if the .db files get processed (or even generated) by an external tool (msi or similar, some site-specific relational database etc.) the characteristics of that tool can affect the order that the records appear in its output.

This might be quite a lot of change to the IOC and other tools just to allow control over the order of fields in qsrv-generated pva structures. Could you add some kind of a 'weight' attribute to the fields and have qsrv order them by weight instead? The presence of a weight attribute tells developers that the field order matters for this particular structure.

**Comment by coretl** [comment]
> This might be quite a lot of change to the IOC and other tools just to allow control over the order of fields in qsrv-generated pva structures. Could you add some kind of a 'weight' attribute to the fields and have qsrv order them by weight instead? The presence of a weight attribute tells developers that the field order matters for this particular structure.

This would work for me, I only need this for NTTable (where the `string[] labels` are assumed to map to the order of the fields in the `structure value`), so I'm happy to add a 'weight' field to the info of each element of `value` so it matches the order of `labels`.

@mdavidsaver would this work for you?

**Comment by ttkorhonen** [comment]
Would it be possible to describe shortly the desired effect or the issue behind this request?

**Comment by coretl** [comment]
For interest, here is a mockup of my usecase: https://github.com/coretl/pvi_qsrv_tags

**Comment by evalott100** [comment]
This is already solved using `putorder`, as found in `base-7.0.7/modules/pva2pva/iocBoot/iocimagedemo`

**Comment by mdavidsaver** [comment]
Specifically, this is a side effect of putorder since the sort is performed before the group type is created.  While not intended, this can be maintained going forward.
