### ISSUE TITLE
QSRV doesn't start automatically

### ISSUE THREAD

**Issue by zhuzzzzzz** [epics-base/pva2pva#57]
After adding these code in xxxAPP/src/Makefile while building IOC , I use ./st.cmd start the IOC but QSRV doesn't start automatically, and in iocsh there is no command related with pva. what is going wrong?
```
myiocname_DBD += qsrv.dbd
myiocname_LIBS += qsrv
```

**Comment by ralphlange** [comment]
What versions of EPICS Base and QSRV are you using?

**Comment by ttkorhonen** [comment]
This page might help: https://epics-base.github.io/pva2pva/
I guess you are missing 
`myiocname_DBD += PVAServerRegister.dbd`

**Comment by zhuzzzzzz** [comment]
> What versions of EPICS Base and QSRV are you using?

base-7.0.7 while I didn't install the pva2pva extension and just use the qsrv shipped with epics base

**Comment by zhuzzzzzz** [comment]
> This page might help: https://epics-base.github.io/pva2pva/ I guess you are missing `myiocname_DBD += PVAServerRegister.dbd`

I add this line and the make operation get error. It suggests "undefined reference to 'pvar_func_registerStartPVAServer'". Do I need to install this pva2pva extension separately?

**Comment by ttkorhonen** [comment]
Are you using the release tar file? If yes, then pva2pva is there already. qsrv is contained in the pva2pva module; if you clone from git, you have to use` --recursive` to get all the necessary submodules.

If you have already successfully built the EPICS base, please check if you have softIocPVA in the 
bin/<your architecture>/ directory. If yes, then you have all you need.
Also, as this is (in my opinion) not a bug but rather a support request, posting to tech-talk might be a better option to get a fast response.

**Comment by ralphlange** [comment]
Here's what we have in src/Makefile to include QSRV (if available).
(Replace \_APPNAME\_ with your application's name.)
```
# Link QSRV (pvAccess Server) if available
ifdef EPICS_QSRV_MAJOR_VERSION
    _APPNAME__LIBS += qsrv
    _APPNAME__LIBS += $(EPICS_BASE_PVA_CORE_LIBS)
    _APPNAME__DBD += PVAServerRegister.dbd
    _APPNAME__DBD += qsrv.dbd
endif
```

That's before linking to the Base libs, i.e., before
```
_APPNAME__LIBS += $(EPICS_BASE_IOC_LIBS)
```
